os: linux
dist: bionic
language: bash
script: make test
stages:
  - test
jobs:
  include:
    - stage: test
      name: 'Ubuntu 18.04 LTS (Bionic Beaver)  [GOAL: install]'
      script:
         - travis_retry sudo make test_install
    - stage: test
      name: 'Ubuntu 19.04 (Disco Dingo), update [GOAL: install] '
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw ubuntu:19.04 /bin/bash -c "apt-get update ; apt-get install -q -y wget curl make procps python ; cd /veles-masternode/; make docker_test_install"